### ISSUE TITLE
Winddirection & windazimuth swapped?

### ISSUE THREAD

**Issue by basschipper** [mjj4791/python-buienradar#1]
Hi,

It seems like the winddirection and windazimuth are swapped?
Also see: home-assistant/home-assistant#8173

If I can help by creating a PR, let me know...

**Comment by mjj4791** [comment]
Bas (@basschipper )
Can you explain a bit more?

I read the referenced post; is the issue you are referring to that the names direction and azimuth are used reversed?
Current output for the library (dev version):
* 'windazimuth': 'NNW'
* 'winddirection': 335

And you were expecting:
* 'winddirection': 'NNW'
* 'windazimuth': 335

This is a simple change I can do; however it also requires a change in the HA components, since otherwise it would result in the units being mixed up...
For both the library and the HA component I have a new version in test; hoping to post this this weekend....

Please let me know if I interpret your issue correctly...

**Comment by mjj4791** [comment]
@basschipper 
I now notice your PR; somehow I was not getting notifications

**Comment by basschipper** [comment]
Yes, you are interpreting it correct.
This will be no problem for HA as it is currently pinned to version 0.4, so we can swap the units in HA later when a new version of this library has been released.

**Comment by mjj4791** [comment]
Merged; However, ests are now failing; will push new unit tests in a bit

**Comment by mjj4791** [comment]
@basschipper 
I am working on an update of the buienradar sensor, this will need a new version of the external library as well

I will incorporate this into thagt PR as well
Thanks for the update!

**Comment by mjj4791** [comment]
Issue is resolved in version 0.7; and is part of homeassitsant >0.49

**Comment by basschipper** [comment]
Nice job, thanks!
